### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by dayfine** [dayfine/capstone#7]
- [ ] Landing / Sign In (No questions yet)
- [ ] Me Page w/ Overview (Kanban w/ all goals/tasks)
- [ ] Can add / edit / delete goals (A Modal/Form)
- [ ] Can add / edit / delete tasks to goals (On a Goal's Panel/Page)
